backend:
  name: github
  repo: sakashi225/alytlife-site
  branch: main

media_folder: "site/static/img"
public_folder: "/static/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "site/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}
