name: Auto Blog Deploy

on:
  push:
    paths:
      - 'site/auto-posts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm init -y
          npm install showdown fs-extra

      - name: Convert Markdown to HTML
        run: |
          mkdir -p site/blog
          node -e "
          const fs = require('fs-extra');
          const showdown  = require('showdown');
          const converter = new showdown.Converter();
          const files = fs.readdirSync('site/auto-posts');
          fs.ensureDirSync('site/blog');
          files.forEach(f => {
            if (f.endsWith('.md')) {
              const data = fs.readFileSync('site/auto-posts/' + f, 'utf8');
              const html = converter.makeHtml(data);
              const out = '<html><head><link rel=\"stylesheet\" href=\"/style.css\"></head><body>' + html + '</body></html>';
              fs.writeFileSync('site/blog/' + f.replace('.md', '.html'), out);
            }
          });
          "

      - name: Commit and push generated HTML
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add site/blog/*.html || true
          git commit -m 'Auto-generated blog posts' || echo 'No changes to commit'
          git push
